### ISSUE TITLE
About root privileges

### ISSUE THREAD

**Issue by qingxp9** [sophsec/ruby-nmap#36]
Run homepage example, it show
    You requested a scan type which requires root privileges.

Then i added "nmap.sudo = true",and it has error too.
````
2.2.0 :015 >   Nmap::Program.scan do |nmap|
2.2.0 :016 >      nmap.sudo = true
2.2.0 :017?>     nmap.syn_scan = true
2.2.0 :018?>     nmap.service_scan = true
2.2.0 :019?>     nmap.os_fingerprint = true
2.2.0 :020?>     nmap.verbose = true
2.2.0 :021?>   
2.2.0 :022 >       nmap.ports = [80]
2.2.0 :023?>     nmap.targets = '192.168.1.*'
2.2.0 :024?>   end
NoMethodError: undefined method `sudo=' for #<Nmap::Task:0x000000012fa5c0 @subtasks={}, @options={}>
	from (irb):16:in `block in irb_binding'
	from /home/qingxp9/.rvm/gems/ruby-2.2.0/gems/rprogram-0.3.2/lib/rprogram/task.rb:32:in `initialize'
	from /home/qingxp9/.rvm/gems/ruby-2.2.0/gems/ruby-nmap-0.8.0/lib/nmap/program.rb:87:in `new'
	from /home/qingxp9/.rvm/gems/ruby-2.2.0/gems/ruby-nmap-0.8.0/lib/nmap/program.rb:87:in `scan'
	from /home/qingxp9/.rvm/gems/ruby-2.2.0/gems/ruby-nmap-0.8.0/lib/nmap/program.rb:49:in `scan'
	from (irb):15
	from /home/qingxp9/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
````

**Comment by postmodern** [comment]
Use [Nmap::Program.sudo_scan](http://www.rubydoc.info/gems/ruby-nmap/Nmap/Program#sudo_scan-class_method).
