### ISSUE TITLE
passing sudo option doesn't seem to work

### ISSUE THREAD

**Issue by raesene** [sophsec/ruby-nmap#5]
In the documentation there's a 'sudo' option that can be used when calling nmap/program to set the sudo flag for the scan.  Calling this doesn't seem to work.

e.g. 

```
1.9.3-p286 :009 > Nmap::Program.scan do |nmap|
1.9.3-p286 :010 >    nmap.sudo = true
1.9.3-p286 :011?>   nmap.syn_scan = true
1.9.3-p286 :012?>   nmap.targets = '192.168.41.8'
1.9.3-p286 :013?> end
NoMethodError: undefined method `sudo=' for #<Nmap::Task:0x9e6d60c @subtasks={}, @options={}>
	from (irb):10:in `block in irb_binding'
	from /home/rorym/.rvm/gems/ruby-1.9.3-p286/gems/rprogram-0.3.0/lib/rprogram/task.rb:32:in `call'
	from /home/rorym/.rvm/gems/ruby-1.9.3-p286/gems/rprogram-0.3.0/lib/rprogram/task.rb:32:in `initialize'
	from /home/rorym/.rvm/gems/ruby-1.9.3-p286/gems/ruby-nmap-0.6.0/lib/nmap/program.rb:75:in `new'
	from /home/rorym/.rvm/gems/ruby-1.9.3-p286/gems/ruby-nmap-0.6.0/lib/nmap/program.rb:75:in `scan'
	from /home/rorym/.rvm/gems/ruby-1.9.3-p286/gems/ruby-nmap-0.6.0/lib/nmap/program.rb:49:in `scan'
	from (irb):9
	from /home/rorym/.rvm/rubies/ruby-1.9.3-p286/bin/irb:16:in `<main>'

```

**Comment by hackeron** [comment]
Please release 0.8.0 :)

**Comment by postmodern** [comment]
0.8.0 is (finally) out!
