### ISSUE TITLE
extconf.rb:4:in `<main>': uninitialized constant Config (NameError)

### ISSUE THREAD

**Issue by KINGSABRI** [sophsec/ruby-nmap#52]
Hello there

getting an error during installation 

```
gem install nmap
Building native extensions. This could take a while...
ERROR:  Error installing nmap:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.4.0/gems/nmap-0.1.0
/usr/bin/ruby2.4 -r ./siteconf20180215-19305-1sr06ec.rb extconf.rb
extconf.rb:4:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.4.0/gems/nmap-0.1.0 for inspection.
Results logged to /var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/nmap-0.1.0/gem_make.out

```

OS: Ubuntu 17.10
Ruby: 2.4 and 2.5

**Comment by KINGSABRI** [comment]
sorry, I was installing 

`nmap` gem not `ruby-nmap`
